"""ordem_servico

Revision ID: 1de86111f8fc
Revises: 26317493bfb7
Create Date: 2015-10-04 18:08:14.738308

"""

# revision identifiers, used by Alembic.
revision = '1de86111f8fc'
down_revision = '26317493bfb7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ordem_servico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('criacao', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('protocolos_ordens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ordem_servico_id', sa.Integer(), nullable=True),
    sa.Column('pendencia_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ordem_servico_id'], ['ordem_servico.id'], ),
    sa.ForeignKeyConstraint(['pendencia_id'], ['pendencia.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('protocolos_ordens')
    op.drop_table('ordem_servico')
    ### end Alembic commands ###
