"""postes pendencias

Revision ID: 1f1f82ae446d
Revises: 576406444d42
Create Date: 2015-09-19 17:47:19.645603

"""

# revision identifiers, used by Alembic.
revision = '1f1f82ae446d'
down_revision = '576406444d42'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('poste',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=255), nullable=True),
    sa.Column('cep', sa.String(length=10), nullable=True),
    sa.Column('estado', sa.String(length=2), nullable=True),
    sa.Column('cidade', sa.Text(), nullable=True),
    sa.Column('bairro', sa.Text(), nullable=True),
    sa.Column('logradouro', sa.Text(), nullable=True),
    sa.Column('numero', sa.Text(), nullable=True),
    sa.Column('tipo', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pendencia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('tipo', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=True),
    sa.Column('obs', sa.Text(), nullable=True),
    sa.Column('poste_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['poste_id'], ['poste.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pendencia')
    op.drop_table('poste')
    ### end Alembic commands ###
