"""equipamento abreviacao

Revision ID: 2884e5622fd7
Revises: e2c0d6f51ee
Create Date: 2015-11-27 13:38:48.038182

"""

# revision identifiers, used by Alembic.
revision = '2884e5622fd7'
down_revision = 'e2c0d6f51ee'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equipamento', sa.Column('abreviacao', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('equipamento', 'abreviacao')
    ### end Alembic commands ###
