"""equipamento ativo

Revision ID: 2ade01d955f4
Revises: 2884e5622fd7
Create Date: 2015-11-27 14:08:29.562277

"""

# revision identifiers, used by Alembic.
revision = '2ade01d955f4'
down_revision = '2884e5622fd7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equipamento', sa.Column('ativo', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('equipamento', 'ativo')
    ### end Alembic commands ###
