"""item_manutencao_status

Revision ID: 2ba0b0c90698
Revises: 32d245c30487
Create Date: 2015-10-12 17:39:47.016101

"""

# revision identifiers, used by Alembic.
revision = '2ba0b0c90698'
down_revision = '32d245c30487'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_manutencao', sa.Column('status', sa.String(length=255), nullable=True))
    op.drop_column('item_manutencao', 'resolvida')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_manutencao', sa.Column('resolvida', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('item_manutencao', 'status')
    ### end Alembic commands ###
