"""pendencia bairro zonas

Revision ID: 322f0e5f9546
Revises: 576406444d42
Create Date: 2015-10-03 23:21:44.646534

"""

# revision identifiers, used by Alembic.
revision = '322f0e5f9546'
down_revision = '576406444d42'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zona_cidade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bairro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=True),
    sa.Column('zona_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['zona_id'], ['zona_cidade.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('poste',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cep', sa.String(length=10), nullable=True),
    sa.Column('estado', sa.String(length=2), nullable=True),
    sa.Column('cidade', sa.Text(), nullable=True),
    sa.Column('bairro_id', sa.Integer(), nullable=True),
    sa.Column('logradouro', sa.Text(), nullable=True),
    sa.Column('numero', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['bairro_id'], ['bairro.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pendencia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('criacao', sa.DateTime(), nullable=True),
    sa.Column('cep', sa.String(length=10), nullable=True),
    sa.Column('estado', sa.String(length=2), nullable=True),
    sa.Column('cidade', sa.Text(), nullable=True),
    sa.Column('bairro_id', sa.Integer(), nullable=True),
    sa.Column('logradouro', sa.Text(), nullable=True),
    sa.Column('numero', sa.Text(), nullable=True),
    sa.Column('poste_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bairro_id'], ['bairro.id'], ),
    sa.ForeignKeyConstraint(['poste_id'], ['poste.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pendencia')
    op.drop_table('poste')
    op.drop_table('bairro')
    op.drop_table('zona_cidade')
    ### end Alembic commands ###
