"""material

Revision ID: 3a6010adbe08
Revises: 3c4ac74a85b3
Create Date: 2015-11-22 17:18:51.372997

"""

# revision identifiers, used by Alembic.
revision = '3a6010adbe08'
down_revision = '3c4ac74a85b3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=True),
    sa.Column('garantia_dias', sa.Integer(), nullable=True),
    sa.Column('preco', sa.Numeric(precision=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('material',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('servico_id', sa.Integer(), nullable=True),
    sa.Column('equipamento_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['equipamento_id'], ['equipamento.id'], ),
    sa.ForeignKeyConstraint(['servico_id'], ['servico.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('material')
    op.drop_table('equipamento')
    ### end Alembic commands ###
