"""servico confirmado

Revision ID: 3b0e1d267b9d
Revises: 2c5e8fc42766
Create Date: 2015-11-27 19:58:08.352516

"""

# revision identifiers, used by Alembic.
revision = '3b0e1d267b9d'
down_revision = '2c5e8fc42766'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servico', sa.Column('confirmado', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('servico', 'confirmado')
    ### end Alembic commands ###
