"""squash

Revision ID: 4bc26760f6b4
Revises: None
Create Date: 2015-10-11 11:58:19.053735

"""

# revision identifiers, used by Alembic.
revision = '4bc26760f6b4'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regiao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ordem_servico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('criacao', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bairro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=True),
    sa.Column('regiao_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['regiao_id'], ['regiao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rua',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('logradouro', sa.String(length=255), nullable=True),
    sa.Column('cep', sa.String(length=255), nullable=True),
    sa.Column('bairro_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bairro_id'], ['bairro.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('poste',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rua_id', sa.Integer(), nullable=True),
    sa.Column('numero', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['rua_id'], ['rua.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item_manutencao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('criacao', sa.DateTime(), nullable=True),
    sa.Column('poste_id', sa.Integer(), nullable=True),
    sa.Column('resolvida', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['poste_id'], ['poste.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('protocolo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cod_protocolo', sa.String(length=255), nullable=True),
    sa.Column('criacao', sa.DateTime(), nullable=True),
    sa.Column('nome_municipe', sa.String(length=255), nullable=True),
    sa.Column('contato_municipe', sa.String(length=255), nullable=True),
    sa.Column('item_manutencao_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_manutencao_id'], ['item_manutencao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item_manutencao_ordem_servico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ordem_servico_id', sa.Integer(), nullable=True),
    sa.Column('item_manutencao_id', sa.Integer(), nullable=True),
    sa.Column('servico_feito', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['item_manutencao_id'], ['item_manutencao.id'], ),
    sa.ForeignKeyConstraint(['ordem_servico_id'], ['ordem_servico.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item_manutencao_ordem_servico')
    op.drop_table('protocolo')
    op.drop_table('item_manutencao')
    op.drop_table('poste')
    op.drop_table('rua')
    op.drop_table('bairro')
    op.drop_table('ordem_servico')
    op.drop_table('regiao')
    ### end Alembic commands ###
