"""squash

Revision ID: 576406444d42
Revises: None
Create Date: 2015-05-05 12:37:36.744086

"""

# revision identifiers, used by Alembic.
revision = '576406444d42'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('protocolo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cod_protocolo', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('cep', sa.String(length=255), nullable=True),
    sa.Column('estado', sa.String(length=2), nullable=True),
    sa.Column('cidade', sa.Text(), nullable=True),
    sa.Column('bairro', sa.Text(), nullable=True),
    sa.Column('logradouro', sa.Text(), nullable=True),
    sa.Column('numero', sa.Text(), nullable=True),
    sa.Column('nome', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('role')
    op.drop_table('protocolo')
    ### end Alembic commands ###
