"""usuario ativo

Revision ID: 8fe36ec8590
Revises: 30ce5c56f77f
Create Date: 2015-10-25 20:38:59.850048

"""

# revision identifiers, used by Alembic.
revision = '8fe36ec8590'
down_revision = '30ce5c56f77f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('active', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'active')
    ### end Alembic commands ###
