"""garantia

Revision ID: df84d083a80
Revises: 3b0e1d267b9d
Create Date: 2015-11-29 20:03:24.349114

"""

# revision identifiers, used by Alembic.
revision = 'df84d083a80'
down_revision = '3b0e1d267b9d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('material', sa.Column('em_garantia', sa.Boolean(), nullable=True))
    op.add_column('preco_equipamento', sa.Column('garantia', sa.Integer(), nullable=True))
    op.drop_column('preco_equipamento', 'garantia_mes')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('preco_equipamento', sa.Column('garantia_mes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('preco_equipamento', 'garantia')
    op.drop_column('material', 'em_garantia')
    ### end Alembic commands ###
